# version: '3'
# services:
#   es01:
#     image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
#     container_name: es01
#     environment:
#       - node.name=es01
#       - cluster.name=es-docker-cluster
#       # - discovery.seed_hosts=192.168.1.15
#       # - cluster.initial_master_nodes=es01,es02
#       - bootstrap.memory_lock=true
#       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#       - network.host=0.0.0.0
#       # - network.publish_host=192.168.1.36
#       - http.port=9200
#       - transport.port=9300
#     ulimits:
#       memlock:
#         soft: -1
#         hard: -1
#     ports:
#       - 9200:9200
#       - 9300:9300

#   kibana:
#     image: docker.elastic.co/kibana/kibana:7.15.0
#     container_name: kibana
#     environment:
#       - ELASTICSEARCH_HOSTS=http://es01:9200
#     ports:
#       - 5601:5601
#     depends_on:
#       - es01

# networks:
#   default:
#     driver: bridge

version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elasticsearch
    environment:
      - discovery.seed_hosts=192.168.1.15
      - discovery.type=single-node
      # - xpack.security.enabled=true
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      # - xpack.security.enabled=true
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
